local _, ns = ...

-- Made by dev/tools/bronze_variants.py: the art in media/bronze/, one file name per line
-- (read case-blind in TextureData.lua). Do not edit by hand; run the tool again.
ns.BRONZE_ART = [[
Button-Backpack-Up
CharacterCreate-LabelFrame
ChatFrame-Atlas
ClockBackground
Common-Input-Border
HelpFrameTab-Active
HelpFrameTab-Inactive
MailItemBorder
Nameplate-Border
QuickJoin-Atlas
SpellBook-SkillLineTab
UI-BackpackBackground
UI-Bag-Components
UI-BankFrame-Floor
UI-Button-KeyRing-Down
UI-Button-KeyRing
UI-Calendar-Button
UI-Character-CharacterTab-BottomLeft
UI-Character-CharacterTab-BottomRight
UI-Character-CharacterTab-L1
UI-Character-CharacterTab-R1
UI-Character-General-BottomLeft
UI-Character-General-BottomRight
UI-Character-General-TopLeft
UI-Character-General-TopRight
UI-Character-ReputationBar
UI-Character-ScrollBar
UI-Character-Skills-BarBorder
UI-Character-StatBackground
UI-ChatIcon-Chat-Disabled
UI-ChatIcon-Chat-Down
UI-ChatIcon-Chat-Up
UI-ChatIcon-ScrollDown-Disabled
UI-ChatIcon-ScrollDown-Down
UI-ChatIcon-ScrollDown-Up
UI-ChatIcon-ScrollEnd-Disabled
UI-ChatIcon-ScrollEnd-Down
UI-ChatIcon-ScrollEnd-Up
UI-ChatIcon-ScrollUp-Disabled
UI-ChatIcon-ScrollUp-Down
UI-ChatIcon-ScrollUp-Up
UI-ChatIcon-Voice-Disabled
UI-ChatIcon-Voice-Down
UI-ChatIcon-Voice-Up
UI-CheckBox-Down
UI-CheckBox-Up
UI-ClassTrainer-HorizontalBar
UI-DialogBox-Border
UI-DialogBox-Header
UI-EmptySlot
UI-LootPanel
UI-MailFrame-InvoiceLine
UI-MainMenu-ScrollDownButton-Disabled
UI-MainMenu-ScrollDownButton-Down
UI-MainMenu-ScrollDownButton-Up
UI-MainMenu-ScrollUpButton-Disabled
UI-MainMenu-ScrollUpButton-Down
UI-MainMenu-ScrollUpButton-Up
UI-Merchant-BottomBorder
UI-Merchant-LabelSlots
UI-MicroButton-abilities-disabled
UI-MicroButton-abilities-down
UI-MicroButton-abilities-up
UI-MicroButton-achievement-disabled
UI-MicroButton-achievement-down
UI-MicroButton-achievement-up
UI-MicroButton-bstore-disabled
UI-MicroButton-bstore-down
UI-MicroButton-bstore-up
UI-MicroButton-characternightelf-disabled
UI-MicroButton-characternightelf-down
UI-MicroButton-characternightelf-up
UI-MicroButton-ej-disabled
UI-MicroButton-ej-down
UI-MicroButton-ej-up
UI-MicroButton-help-disabled
UI-MicroButton-help-down
UI-MicroButton-help-up
UI-MicroButton-lfg-disabled
UI-MicroButton-lfg-down
UI-MicroButton-lfg-up
UI-MicroButton-mainmenu-disabled
UI-MicroButton-mainmenu-down
UI-MicroButton-mainmenu-up
UI-MicroButton-mounts-disabled
UI-MicroButton-mounts-down
UI-MicroButton-mounts-up
UI-MicroButton-quest-disabled
UI-MicroButton-quest-down
UI-MicroButton-quest-up
UI-MicroButton-socials-disabled
UI-MicroButton-socials-down
UI-MicroButton-socials-up
UI-MicroButton-spellbook-disabled
UI-MicroButton-spellbook-down
UI-MicroButton-spellbook-up
UI-MicroButton-talents-disabled
UI-MicroButton-talents-down
UI-MicroButton-talents-up
UI-MicroButton-World-disabled
UI-MicroButton-World-down
UI-MicroButton-World-up
UI-MicroButtonCharacter-Down
UI-MicroButtonCharacter-Up
UI-Minimap-ZoomInButton-Disabled
UI-Minimap-ZoomInButton-Down
UI-Minimap-ZoomInButton-Up
UI-Minimap-ZoomOutButton-Disabled
UI-Minimap-ZoomOutButton-Down
UI-Minimap-ZoomOutButton-Up
UI-OptionsFrame-ActiveTab
UI-OptionsFrame-InActiveTab
UI-Panel-BiggerButton-Disabled
UI-Panel-BiggerButton-Down
UI-Panel-BiggerButton-Up
UI-Panel-Button-Disabled
UI-Panel-Button-Down
UI-Panel-Button-Up
UI-Panel-MinimizeButton-Disabled
UI-Panel-MinimizeButton-Down
UI-Panel-MinimizeButton-Up
UI-Panel-SmallerButton-Disabled
UI-Panel-SmallerButton-Down
UI-Panel-SmallerButton-Up
UI-QuestItemNameFrame
UI-QuestLog-BotLeft
UI-QuestLog-BotRight
UI-QuestLog-Empty-BotLeft
UI-QuestLog-Empty-BotRight
UI-QuestLog-Empty-TopLeft
UI-QuestLog-Empty-TopRight
UI-QuestLog-TopLeft
UI-QuestLog-TopRight
UI-QuestLogDualPane-Left
UI-QuestLogDualPane-Right
UI-QuestLogSortTab-Left
UI-QuestLogSortTab-Middle
UI-QuestLogSortTab-Right
UI-Quickslot
UI-Quickslot2
UI-RotationLeft-Button-Down
UI-RotationLeft-Button-Up
UI-RotationRight-Button-Down
UI-RotationRight-Button-Up
UI-ScrollBar-Knob
UI-ScrollBar-ScrollDownButton-Disabled
UI-ScrollBar-ScrollDownButton-Down
UI-ScrollBar-ScrollDownButton-Up
UI-ScrollBar-ScrollUpButton-Disabled
UI-ScrollBar-ScrollUpButton-Down
UI-ScrollBar-ScrollUpButton-Up
UI-SliderBar-Border
UI-SliderBar-Button-Horizontal
UI-Slot-Background
UI-SpellBook-Tab-Unselected
UI-SpellBook-Tab1-Selected
UI-SpellBook-Tab3-Selected
UI-SpellbookIcon-NextPage-Disabled
UI-SpellbookIcon-NextPage-Down
UI-SpellbookIcon-NextPage-Up
UI-SpellbookIcon-PrevPage-Disabled
UI-SpellbookIcon-PrevPage-Down
UI-SpellbookIcon-PrevPage-Up
UI-SpellbookPanel-BotLeft
UI-SpellbookPanel-BotRight
UI-SpellbookPanel-TopLeft
UI-SpellbookPanel-TopRight
UI-TalentFrame-BotLeft
UI-TalentFrame-BotRight
UI-TradeFrame-EnchantIcon
UIFrame-HTile-Atlas
UIFrame-Inner-Atlas
UIFrame-VTile-Atlas
]]
