local _, ns = ...
local L = ns.L

-- Private table the Options files share.
local O = {}
ns.options = O
O.TITLE = "ClassicUI Forever"

-- key, label, tooltip; parent makes it an indented sub-toggle, grayed while the parent is off; group starts a headed section;
-- radio groups rows where exactly one is on (drop: one drop down row); search adds words the search finds.
-- Order drives the options list, /fcui help and the reload prompt (Core ToggleTree); Status reads it. Kids follow their parent.
local SHOW_TIP = L["OPT_TIP_SHOW_HOVER_HIDE"]
local GRYPHON_TIP = L["OPT_TIP_GRYPHON"]
ns.TOGGLES = {
    { "bronzeTheme", L["OPT_bronzeTheme"], L["OPT_bronzeTheme_TIP"], group = L["GROUP_LOOK"], search = "custom skin color dark mode" },
    { "themeBronze", L["OPT_themeBronze"], L["OPT_themeBronze_TIP"], parent = "bronzeTheme", radio = "theme" },
    { "themeCustom", L["OPT_themeCustom"], L["OPT_themeCustom_TIP"], parent = "bronzeTheme", radio = "theme", search = "rgb hex color" },
    { "themeDark", L["OPT_themeDark"], L["OPT_themeDark_TIP"], parent = "bronzeTheme", radio = "theme" },
    { "panels", L["OPT_panels"], L["OPT_panels_TIP"] },
    { "windowLocksAlways", L["OPT_windowLocksAlways"], L["OPT_windowLocksAlways_TIP"], search = "lock move drag title" },
    { "buttons", L["OPT_buttons"], L["OPT_buttons_TIP"] },
    { "squareIcons", L["OPT_squareIcons"], L["OPT_squareIcons_TIP"], parent = "buttons" },
    { "hideKeyText", L["OPT_hideKeyText"], L["OPT_hideKeyText_TIP"], parent = "buttons" },
    { "castAnim", L["OPT_castAnim"], L["OPT_castAnim_TIP"] },

    { "classicBar", L["OPT_classicBar"], L["OPT_classicBar_TIP"], group = L["GROUP_ACTION_BARS"] },
    { "microTips", L["OPT_microTips"], L["OPT_microTips_TIP"], parent = "classicBar", search = "tooltip" },
    { "hideMicroButtons", L["OPT_hideMicroButtons"], L["OPT_hideMicroButtons_TIP"], parent = "classicBar", search = "micro menu buttons character spellbook talents professions quest guild group finder collections achievements legacy journal housing help" },
    { "hideMicroKeepSize", L["OPT_hideMicroKeepSize"], L["OPT_hideMicroKeepSize_TIP"], parent = "hideMicroButtons" },
    { "hideMicroKeepWidth", L["OPT_hideMicroKeepWidth"], L["OPT_hideMicroKeepWidth_TIP"], parent = "hideMicroButtons", search = "gap background" },
    { "hideMicroSpread", L["OPT_hideMicroSpread"], L["OPT_hideMicroSpread_TIP"], parent = "hideMicroKeepWidth", search = "gap spacing" },
    { "bandHoldsBars", L["OPT_bandHoldsBars"], L["OPT_bandHoldsBars_TIP"], parent = "hideMicroButtons", search = "gap width bar 3" },
    { "hideMicroCharacter", L["OPT_hideMicroCharacter"], L["OPT_hideMicroCharacter_TIP"], parent = "hideMicroButtons" },
    { "hideMicroSpellbook", L["OPT_hideMicroSpellbook"], L["OPT_hideMicroSpellbook_TIP"], parent = "hideMicroButtons" },
    { "hideMicroTalents", L["OPT_hideMicroTalents"], L["OPT_hideMicroTalents_TIP"], parent = "hideMicroButtons" },
    { "hideProfessionsButton", L["OPT_hideProfessionsButton"], L["OPT_hideProfessionsButton_TIP"], parent = "hideMicroButtons" },
    { "hideMicroAchievements", L["OPT_hideMicroAchievements"], L["OPT_hideMicroAchievements_TIP"], parent = "hideMicroButtons" },
    { "hideMicroQuestLog", L["OPT_hideMicroQuestLog"], L["OPT_hideMicroQuestLog_TIP"], parent = "hideMicroButtons" },
    { "hideMicroLegacy", L["OPT_hideMicroLegacy"], L["OPT_hideMicroLegacy_TIP"], parent = "hideMicroButtons" },
    { "hideMicroWorldMap", L["OPT_hideMicroWorldMap"], L["OPT_hideMicroWorldMap_TIP"], parent = "hideMicroButtons" },
    { "hideMicroGuild", L["OPT_hideMicroGuild"], L["OPT_hideMicroGuild_TIP"], parent = "hideMicroButtons" },
    { "hideMicroGroupFinder", L["OPT_hideMicroGroupFinder"], L["OPT_hideMicroGroupFinder_TIP"], parent = "hideMicroButtons" },
    { "hideMicroCollections", L["OPT_hideMicroCollections"], L["OPT_hideMicroCollections_TIP"], parent = "hideMicroButtons" },
    { "lfgMinimapButton", L["OPT_lfgMinimapButton"], L["OPT_lfgMinimapButton_TIP"], parent = "hideMicroGroupFinder", search = "lfg eye dungeon" },
    { "showGroupFinderButton", L["OPT_showGroupFinderButton"], L["OPT_showGroupFinderButton_TIP"], parent = "lfgMinimapButton", radio = "groupFinderButtonShow", drop = true },
    { "hoverGroupFinderButton", L["OPT_hoverGroupFinderButton"], L["OPT_hoverGroupFinderButton_TIP"], parent = "lfgMinimapButton", radio = "groupFinderButtonShow", drop = true },
    { "hideMicroHelp", L["OPT_hideMicroHelp"], L["OPT_hideMicroHelp_TIP"], parent = "hideMicroButtons" },
    { "hideMicroGameMenu", L["OPT_hideMicroGameMenu"], L["OPT_hideMicroGameMenu_TIP"], parent = "hideMicroButtons" },
    { "hideStanceBar", L["OPT_hideStanceBar"], L["OPT_hideStanceBar_TIP"], parent = "classicBar", search = "forms auras shapeshift" },
    { "classicBarSize", L["OPT_classicBarSize"], L["OPT_classicBarSize_TIP"], parent = "classicBar", search = "small size 36 45 game" },
    { "oneBar", L["OPT_oneBar"], L["OPT_oneBar_TIP"], parent = "classicBar" },
    { "eraBagSize", L["OPT_eraBagSize"], L["OPT_eraBagSize_TIP"], parent = "classicBar", search = "bags big large 37" },
    { "reagentBagSlot", L["OPT_reagentBagSlot"], L["OPT_reagentBagSlot_TIP"], parent = "classicBar", radio = "reagentBag" },
    { "reagentBagRound", L["OPT_reagentBagRound"], L["OPT_reagentBagRound_TIP"], parent = "classicBar", radio = "reagentBag" },
    { "reagentBagHover", L["OPT_reagentBagHover"], L["OPT_reagentBagHover_TIP"], parent = "classicBar", radio = "reagentBag" },
    { "hideLatencyBar", L["OPT_hideLatencyBar"], L["OPT_hideLatencyBar_TIP"], parent = "classicBar" },
    { "hideKeyRing", L["OPT_hideKeyRing"], L["OPT_hideKeyRing_TIP"], parent = "classicBar" },
    { "hideBagsArt", L["OPT_hideBagsArt"], L["OPT_hideBagsArt_TIP"], parent = "classicBar" },
    { "hideMicroArt", L["OPT_hideMicroArt"], L["OPT_hideMicroArt_TIP"], parent = "classicBar" },
    { "gryphonsOverBars", L["OPT_gryphonsOverBars"], L["OPT_gryphonsOverBars_TIP"], parent = "classicBar" },
    { "showGryphonLeft", L["OPT_showGryphonLeft"], GRYPHON_TIP, parent = "classicBar", radio = "gryphonLeftShow", drop = true },
    { "hideGryphonLeft", L["OPT_hideGryphonLeft"], GRYPHON_TIP, parent = "classicBar", radio = "gryphonLeftShow", drop = true },
    { "showGryphonRight", L["OPT_showGryphonRight"], GRYPHON_TIP, parent = "classicBar", radio = "gryphonRightShow", drop = true },
    { "hideGryphonRight", L["OPT_hideGryphonRight"], GRYPHON_TIP, parent = "classicBar", radio = "gryphonRightShow", drop = true },
    { "bagsAboveRow", L["OPT_bagsAboveRow"], L["OPT_bagsAboveRow_TIP"], parent = "classicBar" },
    { "hideExtraBars", L["OPT_hideExtraBars"], L["OPT_hideExtraBars_TIP"] },

    { "unitFrames", L["OPT_unitFrames"], L["OPT_unitFrames_TIP"], group = L["GROUP_UNIT_FRAMES"] },
    { "unitFramePlayer", L["OPT_unitFramePlayer"], L["OPT_unitFramePlayer_TIP"], parent = "unitFrames" },
    { "unitFrameTarget", L["OPT_unitFrameTarget"], L["OPT_unitFrameTarget_TIP"], parent = "unitFrames" },
    { "unitFrameFocus", L["OPT_unitFrameFocus"], L["OPT_unitFrameFocus_TIP"], parent = "unitFrames" },
    { "unitFramePet", L["OPT_unitFramePet"], L["OPT_unitFramePet_TIP"], parent = "unitFrames" },
    { "unitFrameParty", L["OPT_unitFrameParty"], L["OPT_unitFrameParty_TIP"], parent = "unitFrames" },
    { "classColorNames", L["OPT_classColorNames"], L["OPT_classColorNames_TIP"], parent = "unitFrames", search = "header background" },
    { "classColorHealth", L["OPT_classColorHealth"], L["OPT_classColorHealth_TIP"], parent = "unitFrames" },
    { "classicStatusFont", L["OPT_classicStatusFont"], L["OPT_classicStatusFont_TIP"], parent = "unitFrames", search = "numbers text size arial" },
    { "barUnitTips", L["OPT_barUnitTips"], L["OPT_barUnitTips_TIP"], parent = "unitFrames" },
    { "hoverBothNumbers", L["OPT_hoverBothNumbers"], L["OPT_hoverBothNumbers_TIP"], parent = "unitFrames" },
    { "thickHealth", L["OPT_thickHealth"], L["OPT_thickHealth_TIP"], parent = "unitFrames", search = "big bigger fat health" },
    { "thickHealthName", L["OPT_thickHealthName"], L["OPT_thickHealthName_TIP"], parent = "thickHealth", radio = "thickHealthStyle", drop = true },
    { "thickHealthPlayer", L["OPT_thickHealthPlayer"], L["OPT_thickHealthPlayer_TIP"], parent = "thickHealth", checks = "thickHealthFrames", drop = true },
    { "thickHealthTarget", L["OPT_thickHealthTarget"], L["OPT_thickHealthTarget_TIP"], parent = "thickHealth", checks = "thickHealthFrames", drop = true },
    { "thickHealthFocus", L["OPT_thickHealthFocus"], L["OPT_thickHealthFocus_TIP"], parent = "thickHealth", checks = "thickHealthFrames", drop = true },
    { "thickHealthMana", L["OPT_thickHealthMana"], L["OPT_thickHealthMana_TIP"], parent = "thickHealth", radio = "thickHealthStyle", drop = true },
    { "eliteFrames", L["OPT_eliteFrames"], L["OPT_eliteFrames_TIP"], parent = "unitFrames" },
    { "eliteFramePlayer", L["OPT_eliteFramePlayer"], L["OPT_eliteFramePlayer_TIP"], parent = "eliteFrames" },
    { "eliteFrameTarget", L["OPT_eliteFrameTarget"], L["OPT_eliteFrameTarget_TIP"], parent = "eliteFrames" },
    { "eliteFrameFocus", L["OPT_eliteFrameFocus"], L["OPT_eliteFrameFocus_TIP"], parent = "eliteFrames" },
    { "hideThreatGlow", L["OPT_hideThreatGlow"], L["OPT_hideThreatGlow_TIP"], parent = "unitFrames", search = "aggro red flash" },
    { "plainNumbers", L["OPT_plainNumbers"], L["OPT_plainNumbers_TIP"], search = "commas thousands separators digits large" },
    { "castBars", L["OPT_castBars"], L["OPT_castBars_TIP"] },
    { "castBarShake", L["OPT_castBarShake"], L["OPT_castBarShake_TIP"], parent = "castBars" },
    { "swingTimers", L["OPT_swingTimers"], L["OPT_swingTimers_TIP"], search = "melee ranged auto attack" },
    { "resourceDisplay", L["OPT_resourceDisplay"], L["OPT_resourceDisplay_TIP"], search = "prd health power under character" },
    { "comboPoints", L["OPT_comboPoints"], L["OPT_comboPoints_TIP"] },
    { "mirrorTimers", L["OPT_mirrorTimers"], L["OPT_mirrorTimers_TIP"] },
    { "hideBuffArrow", L["OPT_hideBuffArrow"], L["OPT_hideBuffArrow_TIP"] },

    { "namePlates", L["OPT_namePlates"], L["OPT_namePlates_TIP"], group = L["GROUP_NAMEPLATES"] },
    { "classColorPlates", L["OPT_classColorPlates"], L["OPT_classColorPlates_TIP"], parent = "namePlates" },
    { "fullPlates", L["OPT_fullPlates"], L["OPT_fullPlates_TIP"] },
    { "hideLastNames", L["OPT_hideLastNames"], L["OPT_hideLastNames_TIP"] },

    { "gameMenu", L["OPT_gameMenu"], L["OPT_gameMenu_TIP"], group = L["GROUP_DIALOGS"] },
    { "settingsPanel", L["OPT_settingsPanel"], L["OPT_settingsPanel_TIP"] },
    { "lootWindow", L["OPT_lootWindow"], L["OPT_lootWindow_TIP"], search = "loot frame" },
    { "lootRoll", L["OPT_lootRoll"], L["OPT_lootRoll_TIP"] },

    { "characterSheet", L["OPT_characterSheet"], L["OPT_characterSheet_TIP"], group = L["GROUP_CHARACTER_AND_SPELLS"] },
    { "statPanes", L["OPT_statPanes"], L["OPT_statPanes_TIP"], parent = "characterSheet" },
    { "equipmentQuickButton", L["OPT_equipmentQuickButton"], L["OPT_equipmentQuickButton_TIP"], parent = "characterSheet" },
    { "weaponSkillDetail", L["OPT_weaponSkillDetail"], L["OPT_weaponSkillDetail_TIP"], parent = "characterSheet" },
    { "spellBook", L["OPT_spellBook"], L["OPT_spellBook_TIP"] },
    { "spellBookTopRank", L["OPT_spellBookTopRank"], L["OPT_spellBookTopRank_TIP"], parent = "spellBook" },
    { "spellBookSearch", L["OPT_spellBookSearch"], L["OPT_spellBookSearch_TIP"], parent = "spellBook" },
    { "talents", L["OPT_talents"], L["OPT_talents_TIP"] },

    { "professionsBook", L["OPT_professionsBook"], L["OPT_professionsBook_TIP"], group = L["GROUP_PROFESSIONS"] },
    { "profBookBig", L["OPT_profBookBig"], L["OPT_profBookBig_TIP"], parent = "professionsBook", search = "big large popout" },
    { "tradeSkill", L["OPT_tradeSkill"], L["OPT_tradeSkill_TIP"] },
    { "tradeSkillSearch", L["OPT_tradeSkillSearch"], L["OPT_tradeSkillSearch_TIP"], parent = "tradeSkill" },
    { "trainer", L["OPT_trainer"], L["OPT_trainer_TIP"] },

    { "questLog", L["OPT_questLog"], L["OPT_questLog_TIP"], group = L["GROUP_QUESTS"] },
    { "questLogDual", L["OPT_questLogDual"], L["OPT_questLogDual_TIP"], parent = "questLog" },
    { "questLevels", L["OPT_questLevels"], L["OPT_questLevels_TIP"], search = "level map filter" },
    { "questTracker", L["OPT_questTracker"], L["OPT_questTracker_TIP"] },
    { "hideObjectiveTracker", L["OPT_hideObjectiveTracker"], L["OPT_hideObjectiveTracker_TIP"], search = "quest watch objectives" },
    { "worldMap", L["OPT_worldMap"], L["OPT_worldMap_TIP"], group = L["GROUP_MAP"] },
    { "mapNavBar", L["OPT_mapNavBar"], L["OPT_mapNavBar_TIP"], parent = "worldMap" },
    { "hideMapQuestButton", L["OPT_hideMapQuestButton"], L["OPT_hideMapQuestButton_TIP"], search = "quest list toggle side panel expand" },
    { "questMapPane", L["OPT_questMapPane"], L["OPT_questMapPane_TIP"] },
    { "mapFade", L["OPT_mapFade"], L["OPT_mapFade_TIP"] },
    { "mapUnlocked", L["OPT_mapUnlocked"], L["OPT_mapUnlocked_TIP"], search = "move map lock" },

    { "whoList", L["OPT_whoList"], L["OPT_whoList_TIP"], group = L["GROUP_SOCIAL"] },
    { "guildRoster", L["OPT_guildRoster"], L["OPT_guildRoster_TIP"] },
    { "groupFinder", L["OPT_groupFinder"], L["OPT_groupFinder_TIP"] },

    { "bags", L["OPT_bags"], L["OPT_bags_TIP"], group = L["GROUP_BAGS"] },
    { "plainQuestItems", L["OPT_plainQuestItems"], L["OPT_plainQuestItems_TIP"], parent = "bags", search = "quest border glow" },
    { "oneBag", L["OPT_oneBag"], L["OPT_oneBag_TIP"] },
    { "bagsBesideBars", L["OPT_bagsBesideBars"], L["OPT_bagsBesideBars_TIP"] },

    { "minimap", L["OPT_minimap"], L["OPT_minimap_TIP"], group = L["GROUP_MINIMAP_AND_CHAT"] },
    { "classicTracking", L["OPT_classicTracking"], L["OPT_classicTracking_TIP"], parent = "minimap" },
    { "showMinimapZone", L["OPT_showMinimapZone"], SHOW_TIP, parent = "minimap", radio = "minimapZoneShow", drop = true },
    { "hoverMinimapZone", L["OPT_hoverMinimapZone"], SHOW_TIP, parent = "minimap", radio = "minimapZoneShow", drop = true },
    { "hideMinimapZone", L["OPT_hideMinimapZone"], SHOW_TIP, parent = "minimap", radio = "minimapZoneShow", drop = true },
    { "showMinimapTracking", L["OPT_showMinimapTracking"], SHOW_TIP, parent = "minimap", radio = "minimapTrackingShow", drop = true },
    { "hoverMinimapTracking", L["OPT_hoverMinimapTracking"], SHOW_TIP, parent = "minimap", radio = "minimapTrackingShow", drop = true },
    { "hideMinimapTracking", L["OPT_hideMinimapTracking"], SHOW_TIP, parent = "minimap", radio = "minimapTrackingShow", drop = true },
    { "showMinimapMail", L["OPT_showMinimapMail"], SHOW_TIP, parent = "minimap", radio = "minimapMailShow", drop = true },
    { "hoverMinimapMail", L["OPT_hoverMinimapMail"], SHOW_TIP, parent = "minimap", radio = "minimapMailShow", drop = true },
    { "hideMinimapMail", L["OPT_hideMinimapMail"], SHOW_TIP, parent = "minimap", radio = "minimapMailShow", drop = true },
    { "showMinimapZoomIn", L["OPT_showMinimapZoomIn"], SHOW_TIP, parent = "minimap", radio = "minimapZoomInShow", drop = true },
    { "hoverMinimapZoomIn", L["OPT_hoverMinimapZoomIn"], SHOW_TIP, parent = "minimap", radio = "minimapZoomInShow", drop = true },
    { "hideMinimapZoomIn", L["OPT_hideMinimapZoomIn"], SHOW_TIP, parent = "minimap", radio = "minimapZoomInShow", drop = true },
    { "showMinimapZoomOut", L["OPT_showMinimapZoomOut"], SHOW_TIP, parent = "minimap", radio = "minimapZoomOutShow", drop = true },
    { "hoverMinimapZoomOut", L["OPT_hoverMinimapZoomOut"], SHOW_TIP, parent = "minimap", radio = "minimapZoomOutShow", drop = true },
    { "hideMinimapZoomOut", L["OPT_hideMinimapZoomOut"], SHOW_TIP, parent = "minimap", radio = "minimapZoomOutShow", drop = true },
    { "showMinimapClock", L["OPT_showMinimapClock"], SHOW_TIP, parent = "minimap", radio = "minimapClockShow", drop = true },
    { "hoverMinimapClock", L["OPT_hoverMinimapClock"], SHOW_TIP, parent = "minimap", radio = "minimapClockShow", drop = true },
    { "hideMinimapClock", L["OPT_hideMinimapClock"], SHOW_TIP, parent = "minimap", radio = "minimapClockShow", drop = true },
    { "showMinimapDiel", L["OPT_showMinimapDiel"], SHOW_TIP, parent = "minimap", radio = "minimapDielShow", drop = true },
    { "hoverMinimapDiel", L["OPT_hoverMinimapDiel"], SHOW_TIP, parent = "minimap", radio = "minimapDielShow", drop = true },
    { "hideMinimapDiel", L["OPT_hideMinimapDiel"], SHOW_TIP, parent = "minimap", radio = "minimapDielShow", drop = true },
    { "showMinimapCalendar", L["OPT_showMinimapCalendar"], SHOW_TIP, parent = "minimap", radio = "minimapCalendarShow", drop = true, search = "date events" },
    { "hoverMinimapCalendar", L["OPT_hoverMinimapCalendar"], SHOW_TIP, parent = "minimap", radio = "minimapCalendarShow", drop = true },
    { "hideMinimapCalendar", L["OPT_hideMinimapCalendar"], SHOW_TIP, parent = "minimap", radio = "minimapCalendarShow", drop = true },
    { "showMinimapCoords", L["OPT_showMinimapCoords"], SHOW_TIP, parent = "minimap", radio = "minimapCoordsShow", drop = true, search = "coords position" },
    { "hoverMinimapCoords", L["OPT_hoverMinimapCoords"], SHOW_TIP, parent = "minimap", radio = "minimapCoordsShow", drop = true },
    { "hideMinimapCoords", L["OPT_hideMinimapCoords"], SHOW_TIP, parent = "minimap", radio = "minimapCoordsShow", drop = true },
    { "hideMinimapBorder", L["OPT_hideMinimapBorder"], L["OPT_hideMinimapBorder_TIP"], parent = "minimap", search = "ring frame" },
    { "hideMinimapHeader", L["OPT_hideMinimapHeader"], L["OPT_hideMinimapHeader_TIP"], parent = "minimap", search = "zone bar top" },
    { "hideButtonBorders", L["OPT_hideButtonBorders"], L["OPT_hideButtonBorders_TIP"], parent = "minimap", search = "ring icons" },
    { "calendarZone", L["OPT_calendarZone"], L["OPT_calendarZone_TIP"], parent = "minimap", radio = "calendarSpot", drop = true, search = "square banner" },
    { "calendarRing", L["OPT_calendarRing"], L["OPT_calendarRing_TIP"], parent = "minimap", radio = "calendarSpot", drop = true },
    { "calendarBehind", L["OPT_calendarBehind"], L["OPT_calendarBehind_TIP"], parent = "minimap", radio = "calendarSpot", drop = true },
    { "minimapButton", L["OPT_minimapButton"], L["OPT_minimapButton_TIP"] },
    { "showOptionsButton", L["OPT_showOptionsButton"], L["OPT_showOptionsButton_TIP"], parent = "minimapButton", radio = "optionsButtonShow", drop = true },
    { "hoverOptionsButton", L["OPT_hoverOptionsButton"], L["OPT_hoverOptionsButton_TIP"], parent = "minimapButton", radio = "optionsButtonShow", drop = true },
    { "minimapCollector", L["OPT_minimapCollector"], L["OPT_minimapCollector_TIP"], search = "minimap icons bag" },
    { "showAddonBag", L["OPT_showAddonBag"], L["OPT_showAddonBag_TIP"], parent = "minimapCollector", radio = "addonBagShow", drop = true },
    { "hoverAddonBag", L["OPT_hoverAddonBag"], L["OPT_hoverAddonBag_TIP"], parent = "minimapCollector", radio = "addonBagShow", drop = true },
    { "classicChat", L["OPT_classicChat"], L["OPT_classicChat_TIP"] },
    { "hideChatButtons", L["OPT_hideChatButtons"], L["OPT_hideChatButtons_TIP"], parent = "classicChat", search = "flush left edge channels voice friends menu" },
    { "hideChatFriends", L["OPT_hideChatFriends"], L["OPT_hideChatFriends_TIP"], parent = "hideChatButtons" },
    { "hideChatChannels", L["OPT_hideChatChannels"], L["OPT_hideChatChannels_TIP"], parent = "hideChatButtons" },
    { "hideChatMenu", L["OPT_hideChatMenu"], L["OPT_hideChatMenu_TIP"], parent = "hideChatButtons" },
    { "hideChatScroll", L["OPT_hideChatScroll"], L["OPT_hideChatScroll_TIP"], parent = "hideChatButtons" },
    { "hideChatBottom", L["OPT_hideChatBottom"], L["OPT_hideChatBottom_TIP"], parent = "hideChatButtons" },
    { "chatScrollBar", L["OPT_chatScrollBar"], L["OPT_chatScrollBar_TIP"], parent = "classicChat", search = "scrollbar right" },

    { "gameDamageNumbers", L["OPT_gameDamageNumbers"], L["OPT_gameDamageNumbers_TIP"], group = L["GROUP_OTHER"] },
    { "damageMeter", L["OPT_damageMeter"], L["OPT_damageMeter_TIP"], search = "dps meter recount details" },
    { "welcomeNote", L["OPT_welcomeNote"], L["OPT_welcomeNote_TIP"] },
    { "addonMessages", L["OPT_addonMessages"], L["OPT_addonMessages_TIP"], search = "chat login lines quiet" },
}

-- Radio rows: key -> its group's keys (Core ToggleChanged keeps exactly one on).
ns.TOGGLE_RADIO = {}
do
    local groups = {}
    for _, entry in ipairs(ns.TOGGLES) do
        local name = entry.radio
        if name then
            local group = groups[name] or {}
            groups[name] = group
            group[#group + 1] = entry[1]
            ns.TOGGLE_RADIO[entry[1]] = group
        end
    end
end
