local _, ns = ...
local L = ns.L

ns.DB_DEFAULTS = {
    dbVersion = 4,
    classicBar = true,
    oneBar = false,
    classicBarSize = false,
    hideStanceBar = false,
    hideMicroButtons = true,
    hideMicroKeepSize = false,
    hideMicroKeepWidth = false,
    bandHoldsBars = false,
    hideMicroSpread = false,
    hideMicroAchievements = false, hideMicroLegacy = true,
    hideMicroHelp = false,
    hideMicroCharacter = false,
    hideMicroSpellbook = false,
    hideMicroTalents = false,
    hideMicroQuestLog = false,
    hideMicroWorldMap = false,
    hideMicroGuild = false,
    hideMicroGroupFinder = true,
    hideMicroCollections = true,
    hideMicroGameMenu = false,
    oneBag = false,
    bagsAboveRow = false,
    bagWindowsFollow = false,
    oneBagColumns = 8,
    barOffsetX = 0,
    barOffsetY = 0,
    barDragged = false,
    -- Band snaps are our own record (a snap writes nothing to the layout), plus the snapped bag scale.
    bagsHeld = false,
    bagsSnapScale = 0,
    barScale = 1,
    buttons = true,
    squareIcons = true,
    bronzeTheme = false,
    themeBronze = true,
    themeDark = false,
    themeCustom = false,
    themeColor = "e69e52",
    castAnim = true,
    professionsBook = true,
    tradeSkill = true,
    trainer = true,
    tradeSkillSearch = true,
    talents = true,
    professionTabs = false,
    whoTabs = false,
    whoColumn = "zone",
    hideBuffArrow = true,
    spellBookTopRank = false,
    bagsBesideBars = true,
    gameDamageNumbers = true,
    -- The layout to go back to, and a pending switch to ours.
    previousLayout = "",
    layoutSelectPending = false,
    layoutSelectTries = 0,
    layoutPrompted = false,
    bandHandedBack = false,
    -- bagsFirst is the band order.
    microScale = 1,
    bagsFirst = false,
    hideExtraBars = true,
    unitFrames = true,
    castBars = true,
    swingTimers = true,
    resourceDisplay = true,
    damageMeter = true,
    classicStatusFont = true,
    castBarShake = false,
    mirrorTimers = true,
    comboPoints = true,
    hideLastNames = false,
    classColorHealth = false,
    hideProfessionsButton = true,
    eraBagSize = true,
    thickHealth = false, thickHealthName = true, thickHealthMana = false,
    thickHealthPlayer = true, thickHealthTarget = true, thickHealthFocus = true, thickEnemyColor = "green",
    classColorNames = false,
    profBookBig = false,
    reagentBagSlot = false,
    reagentBagRound = false,
    reagentBagHover = true,
    hideKeyText = false,
    keyTextSize = 12,
    eliteFrames = false,
    eliteFramePlayer = true,
    eliteFrameTarget = true,
    eliteFrameFocus = true,
    hideThreatGlow = false,
    plainQuestItems = false,
    plainNumbers = false,
    hideStatusMain = false,
    hideStatusSecond = false,
    hoverBothNumbers = true,
    classColorPlates = false,
    mapFade = false,
    welcomeNote = true,
    addonMessages = true,
    barsNote = false,
    barsNoteOff = false,
    minimap = true,
    classicTracking = true,
    calendarRing = false,
    calendarBehind = false,
    calendarZone = true,
    minimapButton = true,
    minimapCollector = false,
    hideLatencyBar = false,
    hideKeyRing = false,
    hideBagsArt = false,
    hideMicroArt = false,
    gryphonsOverBars = false,
    showGryphonLeft = true, hideGryphonLeft = false, showGryphonRight = true, hideGryphonRight = false,
    -- The game's own Hidden on a gryphon (its edit mode dialog, before ours) read into the choice once.
    gryphonHiddenCarried = false,
    mapUnlocked = false,
    minimapCollectorAngle = 132,
    minimapButtonAngle = 200,
    namePlates = true,
    fullPlates = true,
    questTracker = true,
    hideObjectiveTracker = false,
    questLog = true,
    questLogDual = false,
    unitFramePlayer = true,
    unitFrameTarget = true,
    unitFrameFocus = true,
    unitFramePet = true,
    unitFrameParty = true,
    questMapPane = true,
    worldMap = true,
    mapNavBar = false,
    microTips = true,
    plateNameSize = 0,
    swingColorMain = "cast",
    swingColorOff = "darkGold",
    swingColorRanged = "channel",
    swingBorder = 0,
    meterBackground = "marble",
    prdGap = 0,
    meterHeader = 6,
    meterPanPreview = true,
    unitNameSize = 10,
    barUnitTips = true,
    questLevels = false,
    windowLocksAlways = false,
    hideChatButtons = false,
    hideChatFriends = true, hideChatChannels = true, hideChatMenu = true, hideChatScroll = true,
    hideChatBottom = true,
    chatScrollBar = false,
    showMinimapZone = true, hoverMinimapZone = false, hideMinimapZone = false,
    showMinimapTracking = true, hoverMinimapTracking = false, hideMinimapTracking = false,
    showMinimapMail = true, hoverMinimapMail = false, hideMinimapMail = false,
    showMinimapZoomIn = true, hoverMinimapZoomIn = false, hideMinimapZoomIn = false,
    showMinimapZoomOut = true, hoverMinimapZoomOut = false, hideMinimapZoomOut = false,
    showMinimapClock = true, hoverMinimapClock = false, hideMinimapClock = false,
    showMinimapDiel = true, hoverMinimapDiel = false, hideMinimapDiel = false,
    showMinimapCalendar = true, hoverMinimapCalendar = false, hideMinimapCalendar = false,
    showMinimapCoords = true, hoverMinimapCoords = false, hideMinimapCoords = false,
    hideMinimapBorder = false, hideMinimapHeader = false, hideButtonBorders = false,
    showOptionsButton = true, hoverOptionsButton = false,
    showAddonBag = true, hoverAddonBag = false,
    lfgMinimapButton = true, showGroupFinderButton = true, hoverGroupFinderButton = false,
    hideMapQuestButton = false,
    lootWindow = true,
    gameMenu = true,
    lootRoll = false,
    settingsPanel = true,
    panels = true,
    classicChat = true,
    bags = true,
    characterSheet = true,
    statPanes = true,
    weaponSkillDetail = true,
    equipmentQuickButton = false,
    statPaneLeft = "section2",
    statPaneRight = "section3",
    spellBook = true,
    guildRoster = true,
    whoList = true,
    groupFinder = true,
    spellBookSearch = true,
    welcomed = false,
    whatsNewSeen = 0,
    whatsNewFrom = 0,
    surnamesRepaired = false,
    damageNumbersRepaired = false,
    -- "builtin" = client art, "bundled" = the media/ copies, for files the client drops.
    textureSource = "builtin",
}

-- Module walk order by id, applied at login before any init so .toc moves never reorder modules.
-- Matches the registration order.
ns.MODULE_ORDER = {
    "bronzeTheme", "classicBar", "buttons", "castAnim", "pageArrows", "unitFrames", "hideBuffArrow",
    "castBars", "swingTimers", "resourceDisplay", "classicStatusFont", "plainNumbers", "mirrorTimers", "comboPoints", "minimap", "minimapButton", "lfgMinimapButton", "minimapCollector", "namePlates", "classColorPlates",
    "fullPlates", "questTracker", "hideObjectiveTracker", "questLog", "questLogDual", "questLevels", "questMapPane", "panels", "worldMap", "lootWindow", "classicChat", "lootRoll",
    "guildRoster", "whoList", "groupFinder", "hideLastNames", "mapFade", "oneBag", "bags", "characterSheet", "statPanes",
    "spellBook", "spellBookTopRank", "spellBookSearch", "professionsBook", "tradeSkillSearch", "tradeSkill",
    "trainer", "talents", "options", "gameMenu", "tooltips", "clientMenus", "settingsPanel", "damageMeter",
}

-- Reload-only toggles per direction with popup text; unlisted apply live. Owed for art or anchors left on client frames,
-- or client handlers our hand-back leaves tainted (blocked in combat). A child is off while its parent is, unless own = true.
-- Off-only: owed on every turn-off. Both ways: owed while it differs from the session start (pins, spellbook key: once a session).
ns.RELOAD_KEYS = {
    -- The game reads showQuestLevel as its windows build; open ones keep the old titles.
    questLevels = { own = true, on = L["CORE_QUEST_LEVELS_SHOW_EVERYWHERE_ONCE"],
        off = L["CORE_QUEST_LEVELS_LEAVE_THE_MAP"] },
    -- The game redraws bar numbers only as they change, and ours cannot redraw them (the values are secret).
    plainNumbers = { own = true, on = L["CORE_NUMBERS_DROP_SEPARATORS_ONCE"], off = L["CORE_NUMBERS_TAKE_SEPARATORS_ONCE"] },
    classicBar = {
        -- ns.PinBandBars writes the layout only in ns.ReloadForLayout; unpinned, combat moves the bars.
        on = L["CORE_THE_ACTION_BARS_ARE_FIXED"],
        -- Pins stay until ns.UnpinBandBars runs in the reload press; Restore only re-anchors.
        off = L["CORE_THE_EDIT_MODE_LAYOUT_KEEPS"],
    },
    -- PlayerSpellsUtil entries we write back stay tainted (SpellBook TakeOver).
    spellBook = { off = L["CORE_THE_GAME_S_OWN_SPELLBOOK"] },
    -- The micro button's click is handed back by our SetScript, so it runs tainted (Talents TakeButton).
    talents = { off = L["CORE_THE_TALENTS_BUTTON_OPENS_THE"] },
    -- Same for QuestLogMicroButton's click (QuestLog Restore).
    questLog = { off = L["CORE_THE_QUEST_LOG_BUTTON_OPENS"] },
    -- ToggleGuildFrame stays our wrapper once taken (Guild WrapGuildToggle).
    guildRoster = { off = L["CORE_THE_GUILD_KEY_AND_BUTTON"] },
    -- Restore hides the Who tab only; the first tab keeps its name and the row its cut tabs.
    whoList = { off = L["CORE_THE_SOCIAL_WINDOW_S_TABS"] },
    -- Restore hides our host and bars; the client frames keep our anchors and art.
    unitFrames = { off = L["CORE_THE_UNIT_FRAMES_KEEP_SOME"] },
    -- Same, for the player frame (RestorePlayer).
    unitFramePlayer = { off = L["CORE_THE_PLAYER_FRAME_KEEPS_SOME"] },
    -- Target and target of target (RestoreTargetLike).
    unitFrameTarget = { off = L["CORE_THE_TARGET_FRAME_KEEPS_SOME"] },
    -- Focus frame (RestoreTargetLike).
    unitFrameFocus = { off = L["CORE_THE_FOCUS_FRAME_KEEPS_SOME"] },
    -- No hand-back: nothing removes the pet frame's skin.
    unitFramePet = { off = L["CORE_THE_PET_FRAME_KEEPS_THE"] },
    -- Party frames (RestoreParty).
    unitFrameParty = { off = L["CORE_THE_PARTY_FRAMES_KEEP_SOME"] },
    -- Restore puts the atlases back only; fill, spark and flash keep our texture and size.
    castBars = { off = L["CORE_THE_CAST_BARS_KEEP_THE"] },
    -- Restore hides the dark ground only; the bars keep our border, texture and size.
    mirrorTimers = { off = L["CORE_THE_BREATH_AND_FATIGUE_BARS"] },
    -- The client's ComboFrame keeps our anchors (ComboPoints Restore).
    comboPoints = { off = L["CORE_THE_GAME_S_OWN_COMBO"] },
    -- Restore hides the ring art only; buttons, zone name and clock keep the old layout.
    minimap = { off = L["CORE_THE_MINIMAP_S_BUTTONS_AND"] },
    -- Restore hides our pieces; the plates keep our anchors, scale and font.
    namePlates = { off = L["CORE_NAMEPLATES_KEEP_THE_OLD_SIZES"] },
    -- Only the main header is put back; module headers keep the stone art.
    questTracker = { off = L["CORE_THE_OBJECTIVE_TRACKER_KEEPS_THE"] },
    -- Restore hides the floor and parchment; the rows keep the old dress.
    questMapPane = { off = L["CORE_THE_MAP_S_QUEST_LIST"] },
    -- Restore hides the title strips only; dressed windows keep the old frame.
    panels = { off = L["CORE_WINDOWS_ALREADY_OPENED_KEEP_THE"] },
    worldMap = { off = L["CORE_THE_WORLD_MAP_KEEPS_THE"] },
    lootWindow = { off = L["CORE_THE_LOOT_WINDOW_KEEPS_THE"] },
    -- Restore changes nothing; the window keeps our size, buttons and side tabs.
    groupFinder = { off = L["CORE_THE_GROUP_FINDER_KEEPS_THE"] },
    -- Restore changes nothing; dressed bag windows keep the old art.
    bags = { off = L["CORE_BAG_WINDOWS_ALREADY_OPENED_KEEP"] },
    -- No characterSheet: its Restore (GiveBack) undoes everything, side pane and setting too.
    -- Restore changes nothing; the window keeps the book's size with its pieces hidden.
    professionsBook = { off = L["CORE_THE_PROFESSIONS_WINDOW_KEEPS_THE"] },
    -- The client's crafting page stays parked off screen (ns.ShowTradeSkill).
    tradeSkill = { off = "A profession's own crafting page stays out of sight until the interface reloads." },
    -- Restore changes nothing; the menu keeps the old dialog art.
    gameMenu = { off = L["CORE_THE_GAME_MENU_KEEPS_THE"] },
    -- Restore changes nothing; the window keeps the old dialog art.
    settingsPanel = { off = L["CORE_THE_SETTINGS_WINDOW_KEEPS_CLASSIC"] },
}
